const sequelize = require("../config/connection.js");
const { Kitty } = require("../models");

const kittyData = [
    {
        userId: 1,
        kittyName: "Henry",
        kittyStory: "This cat thinks he is a king. He is very loving, spoiled and playful.",
        kittyPicture: "https://res.cloudinary.com/dty2vtbrg/image/upload/v1625863542/kitty_vvava0.png",
        kittyBreed: "Scottish-Fold",
        kittyGender: "Male",
        kittyWeight: "Average",
        kittyColor: "White",
        kittyLocation: "Chicago",
        kittyPersonality: "Playful",
        kittyAge: 3,
        kittyKids: true,
        kittyPets: false,
    },
    {
        userId: 1,
        kittyName: "Felix",
        kittyStory: "Felix is a shy guy looking for a new home, he is good with kids and other animals.",
        kittyPicture: "https://res.cloudinary.com/dty2vtbrg/image/upload/v1625863542/kitty_vvava0.png",
        kittyBreed: "American-Curl",
        kittyGender: "Male",
        kittyWeight: "Underweight",
        kittyColor: "Black",
        kittyLocation: "Atlanta",
        kittyPersonality: "Shy",
        kittyAge: 6,
        kittyKids: true,
        kittyPets: true,
    },
    {
        userId: 1,
        kittyName: "Wesker",
        kittyStory: "I am posting up wesker for adoption because he is eating me out of house and home. I cannot afford him any longer.",
        kittyPicture: "https://res.cloudinary.com/dty2vtbrg/image/upload/v1625863542/kitty_vvava0.png",
        kittyBreed: "Domestic-Short-Hair",
        kittyGender: "Male",
        kittyWeight: "Chonky",
        kittyColor: "Orange",
        kittyLocation: "New York",
        kittyPersonality: "Chill",
        kittyAge: 7,
        kittyKids: false,
        kittyPets: true,
    },
    {
        userId: 1,
        kittyName: "Beerus",
        kittyStory: "Beerus is a very friendly and relaxed cat. Gets along great with other animals.",
        kittyPicture: "https://res.cloudinary.com/dty2vtbrg/image/upload/v1625863542/kitty_vvava0.png",
        kittyBreed: "Sphynx",
        kittyGender: "Male",
        kittyWeight: "Average",
        kittyColor: "White",
        kittyLocation: "Los Angeles",
        kittyPersonality: "Chill",
        kittyAge: 5,
        kittyKids: true,
        kittyPets: true,
    },
    {
        userId: 1,
        kittyName: "Furball",
        kittyStory: "Unfortunately, Furball's last home did not work out. Looking for a loving cat family to adopt her.",
        kittyPicture: "https://res.cloudinary.com/dty2vtbrg/image/upload/v1625863542/kitty_vvava0.png",
        kittyBreed: "Devon-Rex",
        kittyGender: "Female",
        kittyWeight: "Slim-and-Trim",
        kittyColor: "Silver",
        kittyLocation: "San Francisco",
        kittyPersonality: "Playful",
        kittyAge: 9,
        kittyKids: false,
        kittyPets: false,
    }
]

const seedKitty = () => Kitty.bulkCreate(kittyData);

module.exports = seedKitty;
